kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: shop-ingress
  namespace: mega_app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"

spec:
  ingressClassName: 
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shop-svc
            port:
              number: 80

