kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: shop-ingress
  namespace: mega-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_intercept_errors on;
      error_page 404 =200 /index.html;

spec:
  tls:
  - hosts:
      - shop.mrsinghincloud.com     # CHANGE THIS to your actual domain
    secretName: shop-tls-secret
  rules:
  - host: shop.mrsinghincloud.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shop-svc
            port:
              number: 80

