apiVersion: v1
kind: Service
metadata:
  name: shop-svc
  namespace: mega_app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  clusterIP: None
  selector:
    app: mega
